<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Aviaco_V1._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="page-header ">
        <h1>CHARTER</h1>
           </div>




        <%--<p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
        <p><a href="http://www.asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>--%>
 



        
             <asp:GridView ID="dgvCharter" runat="server" CssClass="table table-striped table-hover table-responsive" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnRowEditing="dgvCharter_RowEditing" OnRowUpdated="dgvCharter_RowUpdated" OnRowCancelingEdit="dgvCharter_RowCancelingEdit" OnRowUpdating="dgvCharter_RowUpdating">
                 <Columns>
                     <asp:TemplateField>
                         <ItemTemplate>
                             <asp:HiddenField ID="sID" runat="server" value='<%# Bind("CHAR_TRIP") %>'></asp:HiddenField>

                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Trip">
                         <EditItemTemplate>
                             <asp:Label ID="lblTrip" runat="server" Text='<%# Eval("CHAR_TRIP") %>'></asp:Label>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label1" runat="server" Text='<%# Bind("CHAR_TRIP") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Date">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtDate" runat="server" Text='<%# Bind("CHAR_DATE") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label2" runat="server" Text='<%# Bind("CHAR_DATE") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Account NUMBER">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtNumber" runat="server" Text='<%# Bind("AC_NUMBER") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label3" runat="server" Text='<%# Bind("AC_NUMBER") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Destination">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtDestination" runat="server" Text='<%# Bind("CHAR_DESTINATION") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label4" runat="server" Text='<%# Bind("CHAR_DESTINATION") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Distance">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtDistance" runat="server" Text='<%# Bind("CHAR_DISTANCE") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label5" runat="server" Text='<%# Bind("CHAR_DISTANCE") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Hours Flown">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtHoursFlown" runat="server" Text='<%# Bind("CHAR_HOURS_FLOWN") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label6" runat="server" Text='<%# Bind("CHAR_HOURS_FLOWN") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Hours Wait">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtHoursWait" runat="server" Text='<%# Bind("CHAR_HOURS_WAIT") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label7" runat="server" Text='<%# Bind("CHAR_HOURS_WAIT") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Fuel Gallons">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtFuelGallons" runat="server" Text='<%# Bind("CHAR_FUEL_GALLONS") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label8" runat="server" Text='<%# Bind("CHAR_FUEL_GALLONS") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Oil Quantity">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtOil_Qts" runat="server" Text='<%# Bind("CHAR_OIL_QTS") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label9" runat="server" Text='<%# Bind("CHAR_OIL_QTS") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Customer Code">
                         <EditItemTemplate>
                             <asp:TextBox ID="txtcust_Code" runat="server" Text='<%# Bind("CUS_CODE") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="Label10" runat="server" Text='<%# Bind("CUS_CODE") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                 </Columns>


        </asp:GridView>

    <asp:Button ID="btnNewCharter" runat="server" Text="Button" OnClick="btnNewCharter_Click" />
     
    <asp:Label Text="Text" ID="lblResult" runat="server" />
       

        
  <%--  <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET Web Forms lets you build dynamic websites using a familiar drag-and-drop, event-driven model.
            A design surface and hundreds of controls and components let you rapidly build sophisticated, powerful UI-driven sites with data access.
            </p>
            <p>
                <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301948">Learn more &raquo;</a>
            </p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>
                NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.
            </p>
            <p>
                <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301949">Learn more &raquo;</a>
            </p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>
                You can easily find a web hosting company that offers the right mix of features and price for your applications.
            </p>
            <p>
                <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301950">Learn more &raquo;</a>
            </p>
        </div>
    </div>--%>





</asp:Content>
